/* ============================================================
   lyrics.js — kategoria „teksty / tłumaczenia" do trybu LEKTOR
   ------------------------------------------------------------
   Twist: polski hit OPISANY po angielsku, a światowy po polsku —
   zgadujesz oryginalny tytuł i wykonawcę. Tekst leci na głos
   (lektor) ORAZ na ekranie.

   UWAGA o treści: pole `lyric` to NIE są dosłowne (przetłumaczone)
   teksty piosenek — to autorskie, własnymi słowami WSKAZÓWKI/opisy
   tematu utworu (żeby nie kopiować chronionych tekstów). Jeśli chcesz
   prawdziwe przetłumaczone fragmenty, podmień `lyric` lokalnie w tym
   pliku (offline) — reszta gry zadziała tak samo.

   Format kategorii (jak w categories.js): kind:'lyrics' + songs[].
   Brak `preview`/`artists` — kategoria gra TYLKO w trybie lektor.
   ============================================================ */
window.CATEGORIES = window.CATEGORIES || {};
window.CATEGORIES.lyrics = {

  'tlum-int': {
    label: 'światowe po polsku', desc: 'opis po PL — zgadnij', kind: 'lyrics',
    songs: [
      { title: 'Bohemian Rhapsody', artist: 'Queen', year: '1975',
        lyric: 'Operowa epopeja w kilku częściach: chłopak wyznaje, że właśnie zabił człowieka, błaga matkę o wybaczenie, a chór przywołuje imię diabelskiego błazna.' },
      { title: 'Africa', artist: 'Toto', year: '1982',
        lyric: 'Tęsknota za odległym kontynentem — deszcze nad sawanną, samotne Kilimandżaro i błogosławieństwo dla całej Afryki.' },
      { title: 'Dancing Queen', artist: 'ABBA', year: '1976',
        lyric: 'Siedemnastolatka, królowa parkietu, w piątkowy wieczór tańczy w rytm tamburynu i czuje, że to jej noc.' },
      { title: 'Billie Jean', artist: 'Michael Jackson', year: '1982',
        lyric: 'Mężczyzna gorączkowo zaprzecza, że jest ojcem dziecka kobiety, która twierdzi coś przeciwnego.' },
      { title: 'Smells Like Teen Spirit', artist: 'Nirvana', year: '1991',
        lyric: 'Grunge’owy hymn znudzonego, zbuntowanego pokolenia — ironiczne zaproszenie i poczucie, że „mniej znaczy więcej”.' },
      { title: 'Hotel California', artist: 'Eagles', year: '1977',
        lyric: 'Zmęczony podróżny trafia nocą do luksusowego hotelu, z którego — jak się okazuje — nigdy nie da się wymeldować.' },
      { title: 'Eye of the Tiger', artist: 'Survivor', year: '1982',
        lyric: 'Hymn boksera wracającego na ring: instynkt drapieżnika, wola walki i nieustępliwość wobec rywala.' },
      { title: 'Livin’ on a Prayer', artist: 'Bon Jovi', year: '1986',
        lyric: 'Robotnicza para — on stracił pracę na bocznicy, ona haruje w barze — trzyma się miłości i nadziei mimo biedy.' },
      { title: 'Take On Me', artist: 'a-ha', year: '1985',
        lyric: 'Synthpopowa, błagalna prośba, żeby spróbować być razem — kojarzona z teledyskiem rysowanym ołówkiem.' },
      { title: 'Someone Like You', artist: 'Adele', year: '2011',
        lyric: 'Była dziewczyna odwiedza dawną miłość, życzy mu szczęścia z inną i obiecuje, że znajdzie kogoś takiego jak on.' },
      { title: 'Imagine', artist: 'John Lennon', year: '1971',
        lyric: 'Marzycielska ballada przy fortepianie: wizja świata bez granic, religii i podziałów, w którym ludzie żyją w zgodzie.' },
      { title: 'Hey Jude', artist: 'The Beatles', year: '1968',
        lyric: 'Pocieszająca piosenka skierowana do chłopca, by nie bał się miłości — kończy się długim, wspólnym „na-na-na”.' },
      { title: 'Let It Be', artist: 'The Beatles', year: '1970',
        lyric: 'W trudnej chwili przychodzi ukojenie i rada, by pozwolić sprawom się toczyć; matka szepcze słowa otuchy.' },
      { title: 'Yesterday', artist: 'The Beatles', year: '1965',
        lyric: 'Nostalgiczna ballada o tym, że jeszcze wczoraj kłopoty wydawały się dalekie, a miłość nagle odeszła.' },
      { title: 'Stairway to Heaven', artist: 'Led Zeppelin', year: '1971',
        lyric: 'Rozbudowana rockowa epopeja o kobiecie przekonanej, że kupi sobie drogę do nieba; narasta od delikatnego wstępu po potężne solo.' },
      { title: 'Wish You Were Here', artist: 'Pink Floyd', year: '1975',
        lyric: 'Tęsknota za kimś nieobecnym i rozliczenie z pustką show-biznesu, otwierane dźwiękiem radia i akustycznej gitary.' },
      { title: 'Another Brick in the Wall', artist: 'Pink Floyd', year: '1979',
        lyric: 'Bunt przeciw bezdusznej szkole i tresurze uczniów, z chórem dzieci odmawiających takiej edukacji.' },
      { title: 'Sweet Child o’ Mine', artist: 'Guns N’ Roses', year: '1987',
        lyric: 'Hardrockowa oda do ukochanej z charakterystycznym, dzwoniącym riffem na wejście; jej oczy jak błękitne niebo.' },
      { title: 'November Rain', artist: 'Guns N’ Roses', year: '1992',
        lyric: 'Monumentalna ballada o miłości, która może nie przetrwać; orkiestra, fortepian i przeciągłe solo gitary.' },
      { title: 'Wonderwall', artist: 'Oasis', year: '1995',
        lyric: 'Sztandarowy hymn britpopu braci Gallagherów; tytuł to wymyślone słowo na kogoś, kto może cię ocalić.' },
      { title: 'Don’t Look Back in Anger', artist: 'Oasis', year: '1996',
        lyric: 'Singalong o tym, by nie chować urazy do przeszłości; w refrenie pojawia się tajemnicza Sally.' },
      { title: 'Creep', artist: 'Radiohead', year: '1992',
        lyric: 'Wyznanie kogoś, kto czuje się dziwakiem niegodnym ukochanej osoby, z eksplodującym, zgrzytliwym refrenem.' },
      { title: 'Zombie', artist: 'The Cranberries', year: '1994',
        lyric: 'Gniewny protest song o przemocy i konflikcie w Irlandii Północnej, ze słynnym wokalnym zaśpiewem.' },
      { title: 'Losing My Religion', artist: 'R.E.M.', year: '1991',
        lyric: 'Niepokój i obsesja na punkcie drugiej osoby, niesione brzmieniem mandoliny zamiast typowej gitary.' },
      { title: 'With or Without You', artist: 'U2', year: '1987',
        lyric: 'Napięta ballada o miłości, bez której nie da się żyć, ale i z którą jest ciężko; narasta do katharsis.' },
      { title: 'One', artist: 'U2', year: '1991',
        lyric: 'O dwojgu ludziach, którzy są jednością, ale to nie znaczy, że są tacy sami — gorzki rozrachunek z relacją.' },
      { title: 'Every Breath You Take', artist: 'The Police', year: '1983',
        lyric: 'Pozornie romantyczny, a w istocie niepokojący monolog kogoś, kto śledzi każdy ruch dawnej ukochanej.' },
      { title: 'Englishman in New York', artist: 'Sting', year: '1987',
        lyric: 'Z dystansem i klasą o byciu obcym w wielkim mieście; legalny cudzoziemiec, który pozostaje sobą.' },
      { title: 'Rocket Man', artist: 'Elton John', year: '1972',
        lyric: 'Samotny astronauta tęskni za domem i żoną, traktując loty w kosmos jak zwykłą, męczącą pracę.' },
      { title: 'Your Song', artist: 'Elton John', year: '1970',
        lyric: 'Nieśmiałe wyznanie: chłopak nie ma wiele do zaoferowania, więc daje ukochanej piosenkę o tym, jak cudowne jest życie z nią.' },
      { title: 'I’m Still Standing', artist: 'Elton John', year: '1983',
        lyric: 'Triumfalna deklaracja po rozstaniu: mimo wszystko wciąż stoję na nogach i mam się świetnie.' },
      { title: 'Tears in Heaven', artist: 'Eric Clapton', year: '1992',
        lyric: 'Bolesna, akustyczna ballada ojca po stracie dziecka — pyta, czy syn rozpozna go po drugiej stronie.' },
      { title: 'Nothing Else Matters', artist: 'Metallica', year: '1991',
        lyric: 'Metalowa, ale czuła ballada o bliskości i zaufaniu — nic innego się nie liczy, gdy jesteśmy razem.' },
      { title: 'Enter Sandman', artist: 'Metallica', year: '1991',
        lyric: 'Mroczny riff o dziecięcych koszmarach i piaskunie, który zabiera do krainy snu pełnej lęków.' },
      { title: 'Wind of Change', artist: 'Scorpions', year: '1990',
        lyric: 'Gwizdana ballada-symbol końca zimnej wojny i nadziei na nowy, lepszy świat w przemieniającej się Europie.' },
      { title: 'Highway to Hell', artist: 'AC/DC', year: '1979',
        lyric: 'Rozpędzony rockowy manifest życia na pełnej petardzie, w drodze, która z przymrużeniem oka prowadzi prosto do piekła.' },
      { title: 'Back in Black', artist: 'AC/DC', year: '1980',
        lyric: 'Powrót w wielkim stylu, na czarno, z mocnym riffem — celebracja tego, że wciąż się żyje i gra.' },
      { title: 'Thunderstruck', artist: 'AC/DC', year: '1990',
        lyric: 'Lawinowo narastający riff i okrzyki o byciu rażonym piorunem podczas dzikiej nocy.' },
      { title: 'Sweet Home Alabama', artist: 'Lynyrd Skynyrd', year: '1974',
        lyric: 'Dumna, południowa odpowiedź na krytykę rodzinnego stanu — gitarowy hymn tęsknoty za domem.' },
      { title: 'Born to Run', artist: 'Bruce Springsteen', year: '1975',
        lyric: 'Marzenie, by uciec z dusznego miasteczka samochodem razem z ukochaną, byle dalej, ku wolności.' },
      { title: 'Hallelujah', artist: 'Leonard Cohen', year: '1984',
        lyric: 'Powolna, niemal modlitewna pieśń o miłości i wierze, z biblijnymi obrazami i powtarzanym, łamanym refrenem.' },
      { title: 'The Sound of Silence', artist: 'Simon & Garfunkel', year: '1964',
        lyric: 'Ciemność jako stary przyjaciel i wizja tłumu, który mówi, lecz nie słucha — folkowa cisza zamiast dialogu.' },
      { title: 'Bridge over Troubled Water', artist: 'Simon & Garfunkel', year: '1970',
        lyric: 'Obietnica bycia oparciem dla kogoś w trudnym czasie — jak most ponad wzburzoną wodą.' },
      { title: 'Like a Rolling Stone', artist: 'Bob Dylan', year: '1965',
        lyric: 'Cierpki portret kogoś, kto spadł z wyżyn i musi nauczyć się życia na własną rękę, bez domu i złudzeń.' },
      { title: 'Knockin’ on Heaven’s Door', artist: 'Bob Dylan', year: '1973',
        lyric: 'Umierający odkłada broń i czuje, że puka do nieba — prosta, przejmująca, wielokrotnie przerabiana ballada.' },
      { title: '(I Can’t Get No) Satisfaction', artist: 'The Rolling Stones', year: '1965',
        lyric: 'Zbuntowany riff o frustracji, reklamach i niemożności znalezienia tego, czego się naprawdę pragnie.' },
      { title: 'Paint It Black', artist: 'The Rolling Stones', year: '1966',
        lyric: 'Żałoba i pragnienie, by cały świat pomalować na czarno; charakterystyczne brzmienie sitaru.' },
      { title: 'Angie', artist: 'The Rolling Stones', year: '1973',
        lyric: 'Akustyczne, melancholijne pożegnanie z kobietą o tym imieniu, gdy uczucie już wygasło.' },
      { title: 'House of the Rising Sun', artist: 'The Animals', year: '1964',
        lyric: 'Ponura opowieść o domu w Nowym Orleanie, który zrujnował życie niejednego biedaka; falujące organy.' },
      { title: 'Good Vibrations', artist: 'The Beach Boys', year: '1966',
        lyric: 'Słoneczna, eksperymentalna pop-symfonia o dobrych wibracjach, które wysyła ukochana dziewczyna.' },
      { title: 'California Dreamin’', artist: 'The Mamas & the Papas', year: '1965',
        lyric: 'Tęsknota za ciepłą Kalifornią w szary, zimowy dzień, gdy liście brązowieją, a niebo jest szare.' },
      { title: 'Purple Haze', artist: 'Jimi Hendrix', year: '1967',
        lyric: 'Psychodeliczny gitarowy wir o zamęcie w głowie i fioletowej mgle, która miesza zmysły.' },
      { title: 'My Generation', artist: 'The Who', year: '1965',
        lyric: 'Jąkany, buntowniczy hymn młodości, która nie chce, by starsi mówili jej, jak ma żyć.' },
      { title: 'Born to Be Wild', artist: 'Steppenwolf', year: '1968',
        lyric: 'Motocyklowy hymn wolności i drogi, kojarzony z kinem o wędrówce przez Amerykę; „ciężki metalowy grzmot”.' },
      { title: 'American Pie', artist: 'Don McLean', year: '1971',
        lyric: 'Długa, zakodowana opowieść o „dniu, w którym umarła muzyka” i przemianach amerykańskiego rocka.' },
      { title: 'What a Wonderful World', artist: 'Louis Armstrong', year: '1967',
        lyric: 'Ciepłym, chropawym głosem o zieleni drzew, błękicie nieba i pięknie zwykłego świata.' },
      { title: 'My Way', artist: 'Frank Sinatra', year: '1969',
        lyric: 'Podsumowanie życia u jego kresu: żale były, ale wszystko zrobiłem po swojemu.' },
      { title: 'Fly Me to the Moon', artist: 'Frank Sinatra', year: '1964',
        lyric: 'Swingujące, zalotne wyznanie: zabierz mnie na Księżyc, pozwól bujać wśród gwiazd.' },
      { title: 'Can’t Help Falling in Love', artist: 'Elvis Presley', year: '1961',
        lyric: 'Czuła ballada o tym, że niektórzy po prostu muszą się zakochać, choć rozum podpowiada ostrożność.' },
      { title: 'Jailhouse Rock', artist: 'Elvis Presley', year: '1957',
        lyric: 'Rock’n’rollowa zabawa, w której więźniowie urządzają sobie taneczną imprezę za kratami.' },
      { title: 'Johnny B. Goode', artist: 'Chuck Berry', year: '1958',
        lyric: 'Opowieść o wiejskim chłopaku, który tak świetnie gra na gitarze, że pewnego dnia zobaczy swoje nazwisko w światłach.' },
      { title: 'I Will Survive', artist: 'Gloria Gaynor', year: '1978',
        lyric: 'Discowy hymn kobiety po rozstaniu, która z lęku przekuwa się w siłę i obwieszcza, że da sobie radę sama.' },
      { title: 'Stayin’ Alive', artist: 'Bee Gees', year: '1977',
        lyric: 'Falsetowy, parkietowy hymn przetrwania w wielkim mieście, kojarzony z filmem o gorączce sobotniej nocy.' },
      { title: 'September', artist: 'Earth, Wind & Fire', year: '1978',
        lyric: 'Radosne funkowo-discowe wspomnienie tańca pewnej wrześniowej nocy, z chwytliwym „ba-dee-ya”.' },
      { title: 'YMCA', artist: 'Village People', year: '1978',
        lyric: 'Imprezowy hymn o tym, że młody człowiek zawsze znajdzie miejsce i zabawę w pewnym klubie; literowany refren.' },
      { title: 'Sweet Dreams (Are Made of This)', artist: 'Eurythmics', year: '1983',
        lyric: 'Chłodne synthpopowe motto, że każdy czegoś szuka, a marzenia są z różnego kruszcu.' },
      { title: 'Tainted Love', artist: 'Soft Cell', year: '1981',
        lyric: 'Nerwowy synthpop o ucieczce od zatrutej miłości, która już tylko rani.' },
      { title: 'Girls Just Want to Have Fun', artist: 'Cyndi Lauper', year: '1983',
        lyric: 'Kolorowy hymn o tym, że dziewczyny po prostu chcą się dobrze bawić, mimo wymagań rodziców i świata.' },
      { title: 'Time After Time', artist: 'Cyndi Lauper', year: '1984',
        lyric: 'Czuła obietnica: zawsze, ilekroć się zgubisz, będę czekać i cię odnajdę.' },
      { title: 'Faith', artist: 'George Michael', year: '1987',
        lyric: 'Rockowo-popowy przebój o tym, że tym razem trzeba poczekać na prawdziwe uczucie i mieć trochę wiary.' },
      { title: 'Careless Whisper', artist: 'George Michael', year: '1984',
        lyric: 'Słynne saksofonowe intro i wyrzuty sumienia tancerza, który zdradził i już nigdy nie zatańczy tak beztrosko.' },
      { title: 'Last Christmas', artist: 'Wham!', year: '1984',
        lyric: 'Świąteczny evergreen o sercu podarowanym rok wcześniej i od razu zlekceważonym; w tym roku oddam je komuś wyjątkowemu.' },
      { title: 'Like a Prayer', artist: 'Madonna', year: '1989',
        lyric: 'Pop z gospelowym chórem, mieszający namiętność i religijną ekstazę; głos ukochanego brzmi jak modlitwa.' },
      { title: 'Material Girl', artist: 'Madonna', year: '1984',
        lyric: 'Ironiczny portret dziewczyny żyjącej w materialnym świecie, dla której liczy się zasobność adoratora.' },
      { title: 'Purple Rain', artist: 'Prince', year: '1984',
        lyric: 'Podniosła, gitarowa ballada-tytuł filmu; pragnienie, by widzieć ukochaną kąpiącą się w fioletowym deszczu.' },
      { title: 'Beat It', artist: 'Michael Jackson', year: '1983',
        lyric: 'Rada, by uciekać od ulicznej bijatyki zamiast udowadniać twardość; rockowe solo gitary w popowym hicie.' },
      { title: 'Thriller', artist: 'Michael Jackson', year: '1982',
        lyric: 'Horror na parkiecie: północ, zombie i upiorny śmiech lektora; teledysk-kamień milowy.' },
      { title: 'Smooth Criminal', artist: 'Michael Jackson', year: '1987',
        lyric: 'Pełen napięcia przebój o napadzie w mieszkaniu i powtarzanym pytaniu, czy Annie nic się nie stało.' },
      { title: 'I Want to Break Free', artist: 'Queen', year: '1984',
        lyric: 'Deklaracja wyzwolenia się z toksycznej relacji; teledysk z muzykami w damskich przebraniach.' },
      { title: 'We Are the Champions', artist: 'Queen', year: '1977',
        lyric: 'Stadionowy hymn zwycięzców, którzy walczyli do końca; śpiewany na trybunach całego świata.' },
      { title: 'Don’t Stop Me Now', artist: 'Queen', year: '1978',
        lyric: 'Euforyczny, rozpędzony hymn o byciu w gazie i niepowstrzymanej radości życia tej nocy.' },
      { title: 'Heroes', artist: 'David Bowie', year: '1977',
        lyric: 'Para kochanków pod murem podzielonego miasta, którzy choć przez jeden dzień mogą być bohaterami.' },
      { title: 'Space Oddity', artist: 'David Bowie', year: '1969',
        lyric: 'Major Tom traci łączność z Ziemią i dryfuje samotnie w przestrzeni; odliczanie przed startem.' },
      { title: 'Tutti Frutti', artist: 'Little Richard', year: '1955',
        lyric: 'Eksplozja wczesnego rock’n’rolla z okrzykiem „a-wop-bop-a-loo-bop” i dziką energią.' },
      { title: 'Hit the Road Jack', artist: 'Ray Charles', year: '1961',
        lyric: 'Kobieta wyrzuca faceta za drzwi, powtarzając, żeby spadał i więcej nie wracał.' },
      { title: 'Respect', artist: 'Aretha Franklin', year: '1967',
        lyric: 'Soulowe żądanie szacunku; kobieta literuje, czego oczekuje od partnera po powrocie do domu.' },
      { title: 'No Woman, No Cry', artist: 'Bob Marley', year: '1974',
        lyric: 'Reggae’owe pocieszenie: nie płacz, wszystko będzie dobrze; wspomnienie podwórka i wspólnego ogniska.' },
      { title: 'Could You Be Loved', artist: 'Bob Marley', year: '1980',
        lyric: 'Taneczne reggae z przesłaniem, by nie dać się zwieść i otworzyć na miłość.' },
      { title: 'Nothing Compares 2 U', artist: 'Sinéad O’Connor', year: '1990',
        lyric: 'Przejmująca ballada o pustce po rozstaniu; liczone godziny od odejścia ukochanej osoby, łza w teledysku.' },
      { title: 'Total Eclipse of the Heart', artist: 'Bonnie Tyler', year: '1983',
        lyric: 'Dramatyczna, narastająca ballada o samotności nocą i całkowitym zaćmieniu serca.' },
      { title: 'Take Me to Church', artist: 'Hozier', year: '2013',
        lyric: 'Mroczny, gospelowy przebój stawiający miłość ponad hipokryzją instytucji; ukochana jak świątynia.' },
      { title: 'Rolling in the Deep', artist: 'Adele', year: '2010',
        lyric: 'Soulowa furia po zdradzie: była ukochana obraca ból w ogień i ostrzega, że pożałuje.' },
      { title: 'Hello', artist: 'Adele', year: '2015',
        lyric: 'Telefon do dawnej miłości po latach, z prośbą o wybaczenie i echem „z drugiej strony”.' },
      { title: 'Shape of You', artist: 'Ed Sheeran', year: '2017',
        lyric: 'Rytmiczny popowy hit o poznaniu kogoś w barze i zakochaniu się w sylwetce i sposobie bycia.' },
      { title: 'Someone You Loved', artist: 'Lewis Capaldi', year: '2018',
        lyric: 'Fortepianowa ballada o pustce po odejściu osoby, która była oparciem, gdy było najtrudniej.' },
      { title: 'Poker Face', artist: 'Lady Gaga', year: '2008',
        lyric: 'Elektroniczny przebój o ukrywaniu prawdziwych uczuć za kamienną twarzą jak przy stole karcianym.' },
      { title: 'Shallow', artist: 'Lady Gaga & Bradley Cooper', year: '2018',
        lyric: 'Duet z filmu o narodzinach gwiazdy; pytanie, czy jesteśmy szczęśliwi w płytkim świecie, i wspólny, potężny zaśpiew.' },
      { title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars', year: '2014',
        lyric: 'Funkowy, zadziorny przebój o byciu zbyt stylowym i gorącym; zaproszenie na parkiet z wielką pewnością siebie.' },
      { title: 'Just the Way You Are', artist: 'Bruno Mars', year: '2010',
        lyric: 'Czułe zapewnienie ukochanej, że jest idealna dokładnie taka, jaka jest, i nie musi nic zmieniać.' },
      { title: 'Despacito', artist: 'Luis Fonsi', year: '2017',
        lyric: 'Latynoski, zmysłowy hit o powolnym zbliżaniu się do drugiej osoby; globalny fenomen reggaetonu.' },
      { title: 'Yellow', artist: 'Coldplay', year: '2000',
        lyric: 'Delikatna gitarowa ballada, w której wszystko — gwiazdy, skóra, świat — staje się żółte z miłości do kogoś.' },
      { title: 'Viva la Vida', artist: 'Coldplay', year: '2008',
        lyric: 'Smyczkowy hymn obalonego króla, który niegdyś rządził światem, a teraz zamiata ulice; biją dzwony.' },
      { title: 'Mr. Brightside', artist: 'The Killers', year: '2003',
        lyric: 'Rozpędzony rock o zazdrości i wyobraźni, która dręczy obrazami ukochanej z kimś innym.' },
      { title: 'Seven Nation Army', artist: 'The White Stripes', year: '2003',
        lyric: 'Hipnotyczny, basowy riff stał się stadionowym okrzykiem; samotny bunt przeciw całemu światu.' },
      { title: 'Counting Stars', artist: 'OneRepublic', year: '2013',
        lyric: 'Rytmiczny przebój o pogoni za marzeniami zamiast za pieniędzmi; liczenie gwiazd zamiast trosk.' },
      { title: 'Radioactive', artist: 'Imagine Dragons', year: '2012',
        lyric: 'Mroczny, dudniący hymn o przebudzeniu w nowym, postapokaliptycznym świecie i nowej erze.' },
      { title: 'Believer', artist: 'Imagine Dragons', year: '2017',
        lyric: 'Perkusyjny, agresywny przebój o tym, że ból ukształtował i uczynił z bohatera „wierzącego”.' },
      { title: 'Happy', artist: 'Pharrell Williams', year: '2013',
        lyric: 'Słoneczny, zaraźliwy hit o szczęściu, które rozsadza od środka jak pokój bez dachu.' },
      { title: 'Get Lucky', artist: 'Daft Punk', year: '2013',
        lyric: 'Funkowo-discowy przebój o nocy do białego rana i szczęściu w miłości; gitara w stylu retro.' },
      { title: 'Somebody That I Used to Know', artist: 'Gotye', year: '2011',
        lyric: 'Duet po rozstaniu: oboje przedstawiają swoją wersję, jak z bliskości zostało chłodne „ktoś, kogo kiedyś znałem”.' },
      { title: 'Call Me Maybe', artist: 'Carly Rae Jepsen', year: '2012',
        lyric: 'Beztroski pop o rzuceniu numeru komuś dopiero co poznanemu i nadziei na telefon.' },
      { title: 'Shake It Off', artist: 'Taylor Swift', year: '2014',
        lyric: 'Taneczny przebój o ignorowaniu plotek i hejtu; po prostu się to z siebie strząsa.' },
      { title: 'Blank Space', artist: 'Taylor Swift', year: '2014',
        lyric: 'Autoironiczny portret kobiety o reputacji rozkochującej i niebezpiecznej; puste miejsce na kolejne imię.' },
      { title: 'Blinding Lights', artist: 'The Weeknd', year: '2019',
        lyric: 'Synthwave w stylu lat 80.: nocna jazda przez miasto i tęsknota za dotykiem ukochanej.' },
      { title: 'Levitating', artist: 'Dua Lipa', year: '2020',
        lyric: 'Discopopowy hit o miłości, która unosi w kosmos; taneczny lot ponad ziemią z ukochaną osobą.' },
      { title: 'Bad Guy', artist: 'Billie Eilish', year: '2019',
        lyric: 'Szeptany, minimalistyczny przebój, w którym dziewczyna z przekąsem ogłasza, że to ona jest tym „złym”.' },
      { title: 'Old Town Road', artist: 'Lil Nas X', year: '2019',
        lyric: 'Country-trapowy fenomen o jeździe konno „starą drogą” aż do skutku; kowbojski mem internetu.' },
      { title: 'Sunflower', artist: 'Post Malone & Swae Lee', year: '2018',
        lyric: 'Lekki, melodyjny hit z animowanego filmu o Spider-Manie; ukochana porównana do słonecznika.' },
      { title: 'Stay', artist: 'The Kid LAROI & Justin Bieber', year: '2021',
        lyric: 'Szybki, emocjonalny przebój o błaganiu, by ukochana osoba została, bo bez niej wszystko się sypie.' },
      { title: 'Umbrella', artist: 'Rihanna', year: '2007',
        lyric: 'Obietnica bycia schronieniem dla drugiej osoby w deszczu i burzy; powtarzane „ella, ella”.' },
      { title: 'Diamonds', artist: 'Rihanna', year: '2012',
        lyric: 'Ballada o dwojgu ludziach lśniących jak diamenty na nocnym niebie; blask miłości jak gwiazdy.' },
      { title: 'Firework', artist: 'Katy Perry', year: '2010',
        lyric: 'Motywacyjny hymn o tym, że w każdym drzemie iskra, która może wystrzelić jak fajerwerk.' },
      { title: 'Lose Yourself', artist: 'Eminem', year: '2002',
        lyric: 'Napięty rap z filmu o raperze z Detroit: jedna szansa, by chwycić moment i nie zmarnować życia.' },
      { title: 'Crazy in Love', artist: 'Beyoncé', year: '2003',
        lyric: 'Dęciakowy, energetyczny hit o utracie głowy z miłości; charakterystyczne „uh-oh, uh-oh”.' },
      { title: 'Single Ladies', artist: 'Beyoncé', year: '2008',
        lyric: 'Taneczny manifest samotnych kobiet: jeśli ci na mnie zależało, trzeba było się oświadczyć.' }
    ]
  },

  'tlum-pl': {
    label: 'polskie po angielsku', desc: 'clue in EN — guess', kind: 'lyrics',
    songs: [
      { title: 'Dziwny jest ten świat', artist: 'Czesław Niemen', year: '1967',
        lyric: 'A solemn 1960s protest: the world is strange and full of cruelty, yet the singer still believes people can drive evil away.' },
      { title: 'Jolka, Jolka pamiętasz', artist: 'Budka Suflera', year: '1981',
        lyric: 'A man looks back on secret meetings with a woman in a rented room during grim, grey times.' },
      { title: 'Biała flaga', artist: 'Republika', year: '1981',
        lyric: 'A new-wave anthem about raising a white flag — choosing surrender in love instead of an endless fight.' },
      { title: 'Kolorowe jarmarki', artist: 'Maryla Rodowicz', year: '1977',
        lyric: 'Warm nostalgia for colourful village fairs, balloons and carousels of years long gone.' },
      { title: 'Autobiografia', artist: 'Perfect', year: '1981',
        lyric: 'A whole generation’s memoir set to a birth year of 1960, growing up alongside rock and roll.' },
      { title: 'Słodkiego miłego życia', artist: 'Kombi', year: '1984',
        lyric: 'An ironic toast wishing a sweet, pleasant life while time keeps slipping away.' },
      { title: 'Baśka', artist: 'Wilki', year: '1992',
        lyric: 'A guy proudly brags that his girl has something special that no other woman has.' },
      { title: 'Nic nie może wiecznie trwać', artist: 'Anna Jantar', year: '1977',
        lyric: 'A bittersweet pop reminder that nothing in life can last forever.' },
      { title: 'Mniej niż zero', artist: 'Lady Pank', year: '1983',
        lyric: 'A sharp jab at an empty tabloid celebrity who, in the singer’s eyes, is worth less than zero.' },
      { title: 'Kombinacja', artist: 'Maanam', year: '1985',
        lyric: 'A restless, danceable warning about a tricky scheme and a person you shouldn’t fully trust.' },
      { title: 'Sen o Warszawie', artist: 'Czesław Niemen', year: '1966',
        lyric: 'A longing ballad of a man who dreams of returning to his beloved, rebuilt capital by the river.' },
      { title: 'Małgośka', artist: 'Maryla Rodowicz', year: '1973',
        lyric: 'Friends warn a stubborn girl that the man she loves will only bring her tears, but she won’t listen.' },
      { title: 'Sing-Sing', artist: 'Maryla Rodowicz', year: '1976',
        lyric: 'A playful song comparing a suffocating relationship to being locked up in a famous prison.' },
      { title: 'Krakowski spleen', artist: 'Maanam', year: '1984',
        lyric: 'A grey, rainy morning mood of apathy and waiting for the weather — and the heart — to clear.' },
      { title: 'Lipstick on the Glass', artist: 'Maanam', year: '1985',
        lyric: 'A new-wave song picturing blue, dancing bodies and a smear of lipstick left on glass.' },
      { title: 'Boskie Buenos', artist: 'Maanam', year: '1983',
        lyric: 'A rebellious daydream of escaping dull reality to a glamorous, faraway South American city.' },
      { title: 'Kocham wolność', artist: 'Chłopcy z Placu Broni', year: '1990',
        lyric: 'A breakthrough-era anthem shouting that freedom is the thing the singer loves most of all.' },
      { title: 'Przeżyj to sam', artist: 'Lombard', year: '1983',
        lyric: 'A powerful plea not to just watch life on a screen but to go out and experience it yourself.' },
      { title: 'Szklana pogoda', artist: 'Lombard', year: '1983',
        lyric: 'A tense new-wave song about brittle, glassy weather and a fragile, uneasy state of mind.' },
      { title: 'Chłopaki nie płaczą', artist: 'T.Love', year: '1997',
        lyric: 'A cheeky rock hit insisting, with a wink, that real boys don’t cry no matter what.' },
      { title: 'Warszawa', artist: 'T.Love', year: '1992',
        lyric: 'A restless rock portrait of life in the capital, its streets, crowds and everyday hustle.' },
      { title: 'Arahja', artist: 'Kult', year: '1988',
        lyric: 'A brooding rock epic imagining a city split in two by a wall, with people on the other side.' },
      { title: 'Takie tango', artist: 'Budka Suflera', year: '1992',
        lyric: 'A dramatic ballad comparing the give-and-take of a love affair to the steps of a tango.' },
      { title: 'Dni, których nie znamy', artist: 'Marek Grechuta', year: '1980',
        lyric: 'A poetic, hopeful song urging us to chase the unknown days still ahead of us.' },
      { title: 'Windą do nieba', artist: '2 plus 1', year: '1986',
        lyric: 'A dreamy pop duet about riding an elevator straight up to heaven with someone you love.' },
      { title: 'Chodź, pomaluj mój świat', artist: '2 plus 1', year: '1976',
        lyric: 'A gentle invitation to a loved one to paint the singer’s world in warm, bright colours.' },
      { title: 'Anna Maria', artist: 'Czerwone Gitary', year: '1967',
        lyric: 'A bright 1960s beat song calling out tenderly to a girl with this double name.' },
      { title: 'Biały krzyż', artist: 'Czerwone Gitary', year: '1968',
        lyric: 'A solemn tribute to a fallen soldier remembered by a simple white cross in the forest.' },
      { title: 'Historia jednej znajomości', artist: 'Czerwone Gitary', year: '1971',
        lyric: 'A wistful beat ballad recounting how one chance acquaintance grew, then quietly faded.' },
      { title: 'Tyle słońca w całym mieście', artist: 'Anna Jantar', year: '1974',
        lyric: 'A sunny, optimistic pop hit about a city flooded with sunshine and good feelings.' },
      { title: 'Nie spoczniemy', artist: 'Czerwone Gitary', year: '1977',
        lyric: 'A poetic anthem vowing that we will never rest until we’ve chased every longing of the heart.' },
      { title: 'Wielka woda', artist: 'Izabela Trojanowska', year: '1981',
        lyric: 'A dramatic new-wave hit using a great flood as a metaphor for overwhelming change and emotion.' },
      { title: 'Wsiąść do pociągu', artist: 'Maryla Rodowicz', year: '1972',
        lyric: 'A bittersweet song about boarding any train, just to leave heartbreak and a place behind.' },
      { title: 'Remedium', artist: 'Maryla Rodowicz', year: '1971',
        lyric: 'An upbeat folk-pop recipe for life, listing simple cures for sadness and grey days.' },
      { title: 'Dmuchawce, latawce, wiatr', artist: 'Urszula', year: '1992',
        lyric: 'A breezy pop hit picturing dandelions, kites and wind as symbols of carefree freedom.' },
      { title: 'Konik na biegunach', artist: 'Urszula', year: '1983',
        lyric: 'A new-wave song using a rocking horse as an image of childhood and going nowhere fast.' },
      { title: 'Nie pytaj o Polskę', artist: 'Obywatel G.C.', year: '1988',
        lyric: 'A patriotic rock plea not to ask too many questions about the homeland, but simply to love it.' },
      { title: 'Mamy dla was kwiaty', artist: 'Skaldowie', year: '1968',
        lyric: 'A cheerful 1960s pop tune offering flowers and good cheer to everyone listening.' },
      { title: 'Z kopyta kulig rwie', artist: 'Skaldowie', year: '1968',
        lyric: 'A lively winter romp about a sleigh ride dashing through the snow at full gallop.' },
      { title: 'Józek, nie daruję ci tej nocy', artist: 'Bajm', year: '1983',
        lyric: 'A spirited pop hit in which a woman scolds a man named Józek and won’t forgive him this night.' },
      { title: 'Piechotą do lata', artist: 'Bajm', year: '1984',
        lyric: 'A sunny pop song about walking on foot all the way toward summer and better days.' },
      { title: 'Biała armia', artist: 'Bajm', year: '1990',
        lyric: 'A dramatic pop-rock ballad picturing a “white army” marching through a stormy, emotional landscape.' },
      { title: 'Kryzysowa narzeczona', artist: 'Lady Pank', year: '1983',
        lyric: 'An ironic rock hit about a fair-weather girlfriend who only shows up when times are hard.' },
      { title: 'Zamki na piasku', artist: 'Lady Pank', year: '1984',
        lyric: 'A melodic rock song about fragile dreams built like castles in the sand, doomed to wash away.' },
      { title: 'Stop! Smoking', artist: 'Lady Pank', year: '1986',
        lyric: 'A punchy rock tune built around a blunt plea to quit a bad habit before it’s too late.' },
      { title: 'Mój jest ten kawałek podłogi', artist: 'Kayah', year: '1995',
        lyric: 'A bold, soulful declaration that this patch of dance floor — and her own life — belongs to her.' },
      { title: 'Prawy do lewego', artist: 'Kayah i Goran Bregović', year: '1999',
        lyric: 'A rowdy Balkan-flavoured wedding party song, clapping hands from right to left around the table.' },
      { title: 'Śpij kochanie, śpij', artist: 'Kayah i Goran Bregović', year: '1999',
        lyric: 'A tender lullaby promising to bring a loved one the whole world while they sleep.' },
      { title: 'O mnie się nie martw', artist: 'Kasia Kowalska', year: '1994',
        lyric: 'A strong rock ballad in which a woman tells someone not to worry about her — she’ll cope alone.' },
      { title: 'A to co mam', artist: 'Kasia Kowalska', year: '1994',
        lyric: 'A soulful pop-rock song weighing up the little that she has against what she’s lost in love.' },
      { title: 'Coś optymistycznego', artist: 'Kasia Kowalska', year: '1996',
        lyric: 'A wry rock song where, against all the gloom, she still reaches for something optimistic.' },
      { title: 'Teksański', artist: 'Hey', year: '1995',
        lyric: 'An alt-rock hit with a Texan swagger, mixing restless guitars and a brooding mood.' },
      { title: 'Moja i twoja nadzieja', artist: 'Hey', year: '1994',
        lyric: 'A rousing rock anthem about a shared hope that belongs to both of us at once.' },
      { title: 'Wino', artist: 'Wilki', year: '1993',
        lyric: 'A bluesy rock song comparing a heady, intoxicating love to a glass of wine.' },
      { title: 'Aborygen', artist: 'Wilki', year: '1993',
        lyric: 'A rock hit casting the singer as an outsider, wild and free like an aboriginal soul.' },
      { title: 'Sen o Victorii', artist: 'Dżem', year: '1989',
        lyric: 'A blues-rock dream of a better, freer world, named after a longed-for victory.' },
      { title: 'List do M.', artist: 'Dżem', year: '1991',
        lyric: 'A heartfelt blues ballad written as a letter to someone known only as “M.”' },
      { title: 'Whisky', artist: 'Dżem', year: '1986',
        lyric: 'A smoky blues-rock confession of drowning one’s sorrows in a glass of whisky.' },
      { title: 'Naiwne pytania', artist: 'Dżem', year: '1985',
        lyric: 'A soulful blues song full of naive, childlike questions about why the world is the way it is.' },
      { title: 'Jeszcze będzie przepięknie', artist: 'Sztywny Pal Azji', year: '1988',
        lyric: 'A new-wave anthem promising that, despite everything, life will yet turn out beautiful.' },
      { title: 'Wieża radości, wieża samotności', artist: 'Sztywny Pal Azji', year: '1988',
        lyric: 'A moody rock song contrasting a tower of joy with a tower of loneliness.' },
      { title: 'Niewiele ci mogę dać', artist: 'Bajm', year: '1989',
        lyric: 'A tender pop ballad admitting she can give very little, but offers all her honest love.' },
      { title: 'Trudno tak', artist: 'Ryszard Rynkowski', year: '1992',
        lyric: 'A warm pop hit about how hard it is to say goodbye and let a love simply end.' },
      { title: 'Szczęśliwej drogi już czas', artist: 'Ryszard Rynkowski', year: '1992',
        lyric: 'A sentimental farewell tune wishing everyone a safe journey as it’s time to part.' },
      { title: 'Wehikuł czasu', artist: 'Dżem', year: '1989',
        lyric: 'A blues-rock daydream of a time machine that could carry the singer back to better days.' },
      { title: 'Co ci mogę dać', artist: 'Maanam', year: '1980',
        lyric: 'An early new-wave song wondering, with restless energy, what she can really offer a lover.' },
      { title: 'Cykady na Cykladach', artist: 'Maanam', year: '1991',
        lyric: 'A sun-drenched pop-rock fantasy of cicadas singing on the Greek islands, far from everyday life.' },
      { title: 'To co czuję', artist: 'Edyta Bartosiewicz', year: '1994',
        lyric: 'A soulful rock ballad simply laying bare what the singer truly feels inside.' },
      { title: 'Sen', artist: 'Edyta Bartosiewicz', year: '1997',
        lyric: 'An atmospheric pop-rock song drifting between dream and reality after a love has gone.' },
      { title: 'Jenny', artist: 'Edyta Bartosiewicz', year: '1997',
        lyric: 'A rock hit addressed to a girl named Jenny, urging her to wake up and change her life.' },
      { title: 'Mój przyjacielu', artist: 'Krzysztof Krawczyk', year: '1998',
        lyric: 'A warm, grateful ballad dedicated to a faithful friend who’s always there.' },
      { title: 'Parostatek', artist: 'Krzysztof Krawczyk', year: '1977',
        lyric: 'A nostalgic, gently rolling song comparing life and love to a little steamboat’s journey.' },
      { title: 'Bo jesteś ty', artist: 'Krzysztof Krawczyk', year: '1998',
        lyric: 'A heartfelt pop ballad saying that everything good in life is there simply because of you.' },
      { title: 'Powiedz', artist: 'Ich Troje', year: '1997',
        lyric: 'An emotional pop hit begging a partner to just say what they really feel about the relationship.' },
      { title: 'A wszystko to (bo Ciebie kocham)', artist: 'Ich Troje', year: '2001',
        lyric: 'A dramatic pop ballad explaining that every wild thing he does is all because he loves her.' },
      { title: 'Zachciało Ci się', artist: 'Ich Troje', year: '1996',
        lyric: 'A confrontational pop song accusing a partner of suddenly wanting something completely different.' },
      { title: 'Niepokonani', artist: 'Bajm', year: '1993',
        lyric: 'A soaring pop-rock anthem about two people who, together, feel undefeated.' },
      { title: 'Cisza', artist: 'Budka Suflera', year: '1990',
        lyric: 'A brooding rock ballad about the heavy silence that falls when there’s nothing left to say.' },
      { title: 'Memu miastu na do widzenia', artist: 'Budka Suflera', year: '1979',
        lyric: 'A wistful rock song bidding farewell to one’s home city before moving on.' },
      { title: 'Nie ma wody na pustyni', artist: 'Bajm', year: '1984',
        lyric: 'A pop-rock song using a waterless desert as an image of a dried-up, hopeless situation.' },
      { title: 'Co z nami będzie', artist: 'Lombard', year: '1983',
        lyric: 'A tense new-wave song anxiously asking what will become of the two of us.' },
      { title: 'Zostań', artist: 'Ich Troje', year: '1998',
        lyric: 'A pleading pop ballad asking a loved one to stay just a little longer.' },
      { title: 'Lubię mówić z Tobą', artist: 'Wilki', year: '2002',
        lyric: 'A warm rock song celebrating the simple joy of talking with someone you love.' },
      { title: 'Nie wierz nigdy kobiecie', artist: 'Lady Pank', year: '1984',
        lyric: 'A tongue-in-cheek rock warning never to fully trust a woman’s word.' },
      { title: 'Tańczę z Tobą', artist: 'Maanam', year: '1993',
        lyric: 'A joyful pop-rock celebration of dancing with the one you love.' },
      { title: 'Marcheweczka', artist: 'Lady Pank', year: '1985',
        lyric: 'A quirky rock tune that turns a humble carrot into a cheeky little metaphor.' },
      { title: 'Mała wojna', artist: 'Lombard', year: '1983',
        lyric: 'A new-wave song framing a couple’s constant quarrels as a small private war.' },
      { title: 'Dwie ostatnie noce', artist: 'Bolter', year: '1989',
        lyric: 'A pop-dance hit counting down the last two nights of a fleeting holiday romance.' },
      { title: 'Wakacje z blondynką', artist: 'Lombard', year: '1987',
        lyric: 'A breezy pop-rock memory of a summer holiday spent with a blonde.' },
      { title: 'Tak bardzo się starałem', artist: 'Bajm', year: '1990',
        lyric: 'A wistful pop ballad of a man insisting how very hard he tried to make love work.' },
      { title: 'Ten typ tak ma', artist: 'T.Love', year: '1996',
        lyric: 'A laid-back rock shrug about a guy who is simply built this way and won’t change.' },
      { title: 'King', artist: 'Kult', year: '1990',
        lyric: 'A sardonic rock song crowning an ordinary, flawed man as a self-styled king.' },
      { title: 'Polska', artist: 'Kult', year: '1988',
        lyric: 'A biting, ironic rock portrait of everyday life in the country, named bluntly after it.' },
      { title: 'Po co wolność', artist: 'Kult', year: '1993',
        lyric: 'A provocative rock song questioning what freedom is even for, if it’s wasted.' },
      { title: 'Płomień z nieba', artist: 'Bajm', year: '1990',
        lyric: 'A dramatic pop-rock ballad picturing a flame falling from the sky onto two lovers.' },
      { title: 'Co masz w środku', artist: 'O.N.A.', year: '1996',
        lyric: 'A raw rock song demanding to know what someone truly hides inside.' },
      { title: 'Kiedy powiem sobie dość', artist: 'O.N.A.', year: '1998',
        lyric: 'A powerful rock ballad about the moment a woman finally decides she’s had enough.' }
    ]
  },

  'zagadka-rock': {
    label: 'rock — zagadki', desc: 'kryptyczny opis — zgadnij', kind: 'lyrics',
    songs: [
      { title: 'Smoke on the Water', artist: 'Deep Purple', year: '1972',
        lyric: 'Najsłynniejszy „pierwszy riff” każdego początkującego gitarzysty. Inspiracją był pożar kasyna nad alpejskim jeziorem podczas koncertu.' },
      { title: 'Paranoid', artist: 'Black Sabbath', year: '1970',
        lyric: 'Brytyjscy prekursorzy heavy metalu dograli ten szybki numer w kilka minut jako wypełniacz albumu; rzecz o rozchwianym umyśle.' },
      { title: 'Whole Lotta Love', artist: 'Led Zeppelin', year: '1969',
        lyric: 'Ciężki, zniekształcony riff i psychodeliczny chaos pośrodku — manifest bluesowego hard rocka końca lat 60.' },
      { title: 'Kashmir', artist: 'Led Zeppelin', year: '1975',
        lyric: 'Hipnotyczny, orientalny marsz ze smyczkami i dęciakami; jeden z najbardziej monumentalnych utworów brytyjskiej czwórki, inspirowany pustynną podróżą.' },
      { title: 'Come As You Are', artist: 'Nirvana', year: '1991',
        lyric: 'Falujący, pogłosowy riff i zaproszenie, by przyjść takim, jakim się jest; z przełomowego albumu grunge’owego trio z Seattle.' },
      { title: 'Black Hole Sun', artist: 'Soundgarden', year: '1994',
        lyric: 'Senny, psychodeliczny grunge z surrealistycznym teledyskiem; tytułowe niebiańskie zjawisko ma zmyć cały deszcz.' },
      { title: 'Alive', artist: 'Pearl Jam', year: '1991',
        lyric: 'Debiutancki, gęsty grunge z przeciągłą solówką na koniec; bohater odkrywa rodzinny sekret i mimo wszystko wciąż żyje.' },
      { title: 'Champagne Supernova', artist: 'Oasis', year: '1995',
        lyric: 'Siedmiominutowy, psychodeliczny finał kultowego britpopowego albumu; surrealistyczna podróż gdzieś w stronę gwiazd.' },
      { title: 'Karma Police', artist: 'Radiohead', year: '1997',
        lyric: 'Niepokojąca ballada z fortepianem, narastająca do rozpadu; ironiczna „policja” karząca za drobne przewinienia.' },
      { title: 'Bittersweet Symphony', artist: 'The Verve', year: '1997',
        lyric: 'Pętla smyczkowa z coveru Stonesów napędza ten gorzko-słodki hymn o byciu niewolnikiem pieniędzy; spór o prawa autorskie przeszedł do historii.' },
      { title: 'Killing in the Name', artist: 'Rage Against the Machine', year: '1992',
        lyric: 'Funkowo-metalowy protest przeciw rasizmowi i ślepemu posłuszeństwu; kończy się powtarzanym, buntowniczym okrzykiem.' },
      { title: '1979', artist: 'The Smashing Pumpkins', year: '1996',
        lyric: 'Marzycielski, zapętlony numer o nudzie i wolności nastolatków z przedmieść; tytuł to rok, nie tekst.' },
      { title: 'Basket Case', artist: 'Green Day', year: '1994',
        lyric: 'Pop-punkowy hit o nerwicy i paranoi, wyśpiewany z przymrużeniem oka przez kalifornijskie trio.' },
      { title: 'Boulevard of Broken Dreams', artist: 'Green Day', year: '2004',
        lyric: 'Z rockowej opery o amerykańskim everymanie; samotny spacer pustą aleją, gdzie cień jest jedynym towarzystwem.' },
      { title: 'In the End', artist: 'Linkin Park', year: '2000',
        lyric: 'Rap-rockowy hit z fortepianowym motywem; gorzka konkluzja, że mimo starań i tak nie miało to znaczenia.' },
      { title: 'Numb', artist: 'Linkin Park', year: '2003',
        lyric: 'Nu-metalowy krzyk kogoś przytłoczonego cudzymi oczekiwaniami; o byciu zdrętwiałym i nieswoim.' },
      { title: 'Chop Suey!', artist: 'System of a Down', year: '2001',
        lyric: 'Ormiańsko-amerykański zespół miesza ostre riffy z nagłą, niemal liturgiczną ciszą; gwałtowne zmiany tempa i nastroju.' },
      { title: 'Bring Me to Life', artist: 'Evanescence', year: '2003',
        lyric: 'Gotycki rock z żeńskim wokalem i męskim growlem w refrenie; prośba, by ktoś obudził zamrożone serce.' },
      { title: 'Everlong', artist: 'Foo Fighters', year: '1997',
        lyric: 'Pędzący, emocjonalny rock byłego perkusisty grunge’owej legendy; marzenie, by chwila z ukochaną trwała wiecznie.' },
      { title: 'The Pretender', artist: 'Foo Fighters', year: '2007',
        lyric: 'Cicho-głośny schemat eksplodujący w buntowniczy refren; sprzeciw wobec narzucania, kim masz być.' },
      { title: 'Under the Bridge', artist: 'Red Hot Chili Peppers', year: '1991',
        lyric: 'Delikatne gitarowe intro i wyznanie samotności w wielkim mieście; kalifornijski zespół o najmroczniejszym okresie wokalisty.' },
      { title: 'Californication', artist: 'Red Hot Chili Peppers', year: '1999',
        lyric: 'Melodyjny rock o ciemnej stronie świata snów z Zachodniego Wybrzeża; przemysł rozrywki jako fałszywy raj.' },
      { title: 'Dream On', artist: 'Aerosmith', year: '1973',
        lyric: 'Wczesna, fortepianowo-rockowa ballada bostońskiej kapeli, kończąca się wysokim wrzaskiem wokalisty; o upływie czasu i marzeniach.' },
      { title: 'Walk This Way', artist: 'Aerosmith', year: '1975',
        lyric: 'Funkowy riff, który dekadę później odżył w przełomowym rapowo-rockowym mariażu; zadziorna opowieść o nastoletniej inicjacji.' },
      { title: 'You Give Love a Bad Name', artist: 'Bon Jovi', year: '1986',
        lyric: 'Strzał i okrzyk na wejście, potem stadionowy refren; o kobiecie, która rani jak strzała w samo serce.' },
      { title: 'Don’t Stop Believin’', artist: 'Journey', year: '1981',
        lyric: 'Fortepianowy wstęp i niegasnący refren-zachęta; małomiasteczkowa dziewczyna i chłopak w nocnym pociągu donikąd. Hymn karaoke.' },
      { title: 'More Than a Feeling', artist: 'Boston', year: '1976',
        lyric: 'Warstwowe gitary i czysty, wysoki wokal; wspomnienie, które wraca, gdy w radiu zagra dawna piosenka.' },
      { title: 'Should I Stay or Should I Go', artist: 'The Clash', year: '1982',
        lyric: 'Surowy punkrockowy dylemat z hiszpańskimi wstawkami w tle; zostać czy odejść — oto pytanie.' },
      { title: 'Barracuda', artist: 'Heart', year: '1977',
        lyric: 'Galopujący riff i siostrzany duet prowadzący jeden z najostrzejszych rockowych kawałków lat 70.; gniew ubrany w morskiego drapieżnika.' },
      { title: 'Heart-Shaped Box', artist: 'Nirvana', year: '1993',
        lyric: 'Cicho-głośny grunge z surrealistycznym, niepokojącym teledyskiem; uwikłanie w obezwładniającą relację.' },
      { title: 'Sultans of Swing', artist: 'Dire Straits', year: '1978',
        lyric: 'Płynne, czyste partie gitary i opowieść o nieznanym zespole grającym jazz w pustawym pubie; brytyjski debiut końca lat 70.' },
      { title: 'Anarchy in the U.K.', artist: 'Sex Pistols', year: '1976',
        lyric: 'Manifest brytyjskiego punka; zgrzytliwy okrzyk anarchisty, który wstrząsnął sceną w połowie lat 70.' }
    ]
  },

  'zagadka-pop': {
    label: 'pop — zagadki', desc: 'kryptyczny opis — zgadnij', kind: 'lyrics',
    songs: [
      { title: '...Baby One More Time', artist: 'Britney Spears', year: '1998',
        lyric: 'Debiut nastoletniej gwiazdy z teledyskiem w szkolnym mundurku; taneczny przebój, który zdefiniował przełom tysiącleci w popie.' },
      { title: 'Toxic', artist: 'Britney Spears', year: '2003',
        lyric: 'Smyczkowy, „bollywoodzki” sampel i syk w tle; uzależnienie od kogoś porównane do trucizny.' },
      { title: 'Wannabe', artist: 'Spice Girls', year: '1996',
        lyric: 'Debiut brytyjskiej grupy pięciu dziewczyn; warunkiem przyjaźni jest dogadanie się z koleżankami. Hasło „girl power”.' },
      { title: 'Believe', artist: 'Cher', year: '1998',
        lyric: 'Wielki przebój z celowo zniekształconym, „robotycznym” wokalem; taniec po rozstaniu i pytanie o życie po miłości.' },
      { title: 'Genie in a Bottle', artist: 'Christina Aguilera', year: '1999',
        lyric: 'Debiut nastoletniej wokalistki o ogromnej skali głosu; metafora dżina, którego trzeba „odpowiednio potrzeć”.' },
      { title: 'I Want It That Way', artist: 'Backstreet Boys', year: '1999',
        lyric: 'Chłopięcy zespół z Florydy; harmonijny refren, którego sens do dziś bywa żartobliwie rozkładany na czynniki.' },
      { title: 'Bye Bye Bye', artist: 'NSYNC', year: '2000',
        lyric: 'Marionetkowy teledysk i pożegnanie z toksyczną relacją; jeden z największych hitów boysbandu z Justinem T.' },
      { title: 'MMMBop', artist: 'Hanson', year: '1997',
        lyric: 'Trzej młodzi bracia i refren zbudowany z bezsensownych sylab; ulotność chwili ukryta w beztroskim popie.' },
      { title: 'No Scrubs', artist: 'TLC', year: '1999',
        lyric: 'Żeńskie trio R&B odprawia z kwitkiem faceta bez ambicji i własnego auta; definicja pewnego pogardliwego określenia.' },
      { title: 'Vogue', artist: 'Madonna', year: '1990',
        lyric: 'House’owy hołd dla nowojorskiej sceny tanecznej i dawnego Hollywood; instrukcja, jak pozować na parkiecie.' },
      { title: 'Bad Romance', artist: 'Lady Gaga', year: '2009',
        lyric: 'Awangardowy teledysk i chwytliwe „ra-ra” w refrenie; pragnienie miłości razem z całym jej bagażem i bliznami.' },
      { title: 'Just Dance', artist: 'Lady Gaga', year: '2008',
        lyric: 'Debiutancki, elektroniczny hit o nocy w klubie, gdy wszystko wiruje, a jedyna rada to po prostu tańczyć.' },
      { title: 'I Kissed a Girl', artist: 'Katy Perry', year: '2008',
        lyric: 'Przebojowy, prowokacyjny pop o eksperymentalnym pocałunku i smaku wisienkowego błyszczyku.' },
      { title: 'Roar', artist: 'Katy Perry', year: '2013',
        lyric: 'Motywacyjny hymn przemiany z ofiary w mistrzynię; ryk drapieżnika jako symbol odzyskanej siły.' },
      { title: 'New Rules', artist: 'Dua Lipa', year: '2017',
        lyric: 'Lista zasad, jak nie wrócić do byłego; taneczny przebój brytyjskiej wokalistki z choreografią w hotelu.' },
      { title: 'Can’t Feel My Face', artist: 'The Weeknd', year: '2015',
        lyric: 'Popowo-funkowy hit w stylu retro, w którym uczucie (lub używka) odbiera czucie w twarzy; kanadyjski wokalista.' },
      { title: 'Watermelon Sugar', artist: 'Harry Styles', year: '2019',
        lyric: 'Słoneczny, retro-popowy przebój byłego członka boysbandu; letnia zmysłowość ukryta za metaforą owocu.' },
      { title: 'As It Was', artist: 'Harry Styles', year: '2022',
        lyric: 'Pulsujący synth-pop o tym, że nic już nie jest jak dawniej; jeden z największych hitów początku lat 20.' },
      { title: 'Love Yourself', artist: 'Justin Bieber', year: '2015',
        lyric: 'Akustyczny, zgryźliwy numer współtworzony przez Eda Sheerana; uprzejma rada dla byłej, by pokochała samą siebie.' },
      { title: 'Sorry', artist: 'Justin Bieber', year: '2015',
        lyric: 'Tropikalny, taneczny pop; wielokrotne przepraszanie po rozstaniu i pytanie, czy jest jeszcze szansa.' },
      { title: 'Wrecking Ball', artist: 'Miley Cyrus', year: '2013',
        lyric: 'Dramatyczna ballada z kontrowersyjnym teledyskiem; miłość, która zburzyła wszystko jak kula wyburzeniowa.' },
      { title: 'Royals', artist: 'Lorde', year: '2013',
        lyric: 'Minimalistyczny, perkusyjny debiut nastolatki z Nowej Zelandii; ironiczny dystans wobec luksusu z popowych klipów.' },
      { title: 'Hips Don’t Lie', artist: 'Shakira', year: '2006',
        lyric: 'Kolumbijska gwiazda i trąbkowy sampel; taneczny hit, w którym ciało zdradza prawdziwe emocje.' },
      { title: 'Waka Waka', artist: 'Shakira', year: '2010',
        lyric: 'Oficjalny hymn mundialu w RPA oparty na afrykańskiej melodii; zaraźliwy refren o byciu na boisku.' },
      { title: 'Livin’ la Vida Loca', artist: 'Ricky Martin', year: '1999',
        lyric: 'Latynoska eksplozja, która rozpoczęła pop-boom przełomu wieków; uwodzicielka prowadząca „szalone życie”.' },
      { title: 'Bleeding Love', artist: 'Leona Lewis', year: '2007',
        lyric: 'Brytyjska zwyciężczyni talent-show; potężna ballada o sercu krwawiącym z miłości mimo ostrzeżeń.' },
      { title: 'Titanium', artist: 'David Guetta ft. Sia', year: '2011',
        lyric: 'Klubowy hit z mocnym żeńskim wokalem; deklaracja, że ciosy odbijają się jak od metalu.' },
      { title: 'Chandelier', artist: 'Sia', year: '2014',
        lyric: 'Australijska wokalistka i taniec dziewczynki w teledysku; impreza jako ucieczka, huśtanie się u żyrandola.' },
      { title: 'Wake Me Up', artist: 'Avicii', year: '2013',
        lyric: 'Szwedzki DJ łączy folk z EDM; akustyczna gitara i głos o zagubieniu oraz czekaniu, aż ktoś obudzi.' },
      { title: 'Closer', artist: 'The Chainsmokers', year: '2016',
        lyric: 'Duet EDM-pop o przypadkowym spotkaniu byłych w hotelu; wspomnienie materaca kupionego od znajomego.' },
      { title: 'Hung Up', artist: 'Madonna', year: '2005',
        lyric: 'Discopowy powrót oparty na sampel ABBY; oczekiwanie na telefon i czas, który ucieka — tik-tak.' },
      { title: 'TiK ToK', artist: 'Kesha', year: '2009',
        lyric: 'Imprezowy electro-pop o budzeniu się i zabawie do upadłego; mycie zębów rzekomo czymś mocniejszym.' }
    ]
  },

  'rap-pl-opis': {
    label: 'rap PL — opisy', desc: 'opis po PL — zgadnij', kind: 'lyrics',
    songs: [
      { title: 'Jestem Bogiem', artist: 'Paktofonika', year: '2000',
        lyric: 'Manifest pewności siebie i wiary we własną wartość; kultowy kawałek katowickiej grupy z debiutu, owiany legendą po śmierci Magika.' },
      { title: 'Mam wrażenie', artist: 'Grammatik', year: '2000',
        lyric: 'Refleksyjny, melancholijny numer Eldo i Pezeta o niepokoju i przeczuciu, że coś jest nie tak ze światem wokół.' },
      { title: 'Scyzoryk', artist: 'Liroy', year: '1995',
        lyric: 'Jeden z pierwszych wielkich polskich hitów hip-hopowych; zadziorny kawałek, który wprowadził rap do mainstreamu.' },
      { title: 'Tak jak w getcie', artist: 'Molesta Ewenement', year: '1998',
        lyric: 'Surowa opowieść o życiu na warszawskim blokowisku — bieda, codzienność i kodeks ulicy z perspektywy podwórka.' },
      { title: 'Głucha noc', artist: 'Peja / Slums Attack', year: '2001',
        lyric: 'Mroczny, gniewny obraz nocnego miasta i twardej rzeczywistości poznańskiego rapera.' },
      { title: 'Tabasko', artist: 'O.S.T.R.', year: '2002',
        lyric: 'Tytułowy kawałek z albumu łódzkiego rapera i skrzypka; ostry jak sos, popis flow nad jazzującym bitem.' },
      { title: 'W aucie', artist: 'WWO', year: '2004',
        lyric: 'Klimatyczny przebój o jeździe przez miasto nocą; jeden z najbardziej rozpoznawalnych kawałków warszawskiej ekipy.' },
      { title: 'Co mamy, a co chcemy mieć', artist: 'Pezet / Noon', year: '2004',
        lyric: 'Zadumany numer o marzeniach i niezadowoleniu — różnica między tym, co się ma, a czego się pragnie.' },
      { title: 'Czarno na białym', artist: 'Abradab', year: '2004',
        lyric: 'Solowy hit członka Kaliber 44; pozytywny, melodyjny kawałek o stawianiu sprawy jasno.' },
      { title: 'Pomysł na siebie', artist: 'Łona i Webber', year: '2001',
        lyric: 'Inteligentny, ironiczny tekst o szukaniu pomysłu na życie; szczeciński duet znany z gry słów.' },
      { title: 'Real', artist: 'donGURALesko', year: '2007',
        lyric: 'Energetyczny kawałek poznańskiego rapera o byciu prawdziwym i wiernym sobie.' },
      { title: 'Wielkie Joł', artist: 'Tede', year: '2004',
        lyric: 'Przebojowy, imprezowy hit z charakterystycznym okrzykiem; jeden z najbardziej rozpoznawalnych numerów warszawskiego rapera.' },
      { title: 'Nmisie', artist: 'Sokół feat. Pono', year: '2007',
        lyric: 'Ironiczny portret naiwnych „misiów” łatwo dających się oszukać; mocny, wpadający w ucho refren.' },
      { title: 'Sytuacje', artist: 'Mezo', year: '2005',
        lyric: 'Melodyjny rap o codziennych wyborach; przebój łączący rap ze śpiewanym refrenem.' },
      { title: 'Patointeligencja', artist: 'Mata', year: '2020',
        lyric: 'Głośny debiut nastoletniego rapera; ostry portret życia uprzywilejowanej młodzieży z elitarnego liceum, który wywołał ogólnopolską dyskusję.' },
      { title: 'Następna stacja', artist: 'Taco Hemingway', year: '2015',
        lyric: 'Refleksyjny, miastowy kawałek o przemijaniu i kolejnych etapach życia; wczesny przebój warszawskiego rapera.' },
      { title: 'Polskie Tango', artist: 'Taco Hemingway', year: '2020',
        lyric: 'Gorzki komentarz o kraju i pokoleniu uwięzionym w tańcu w miejscu; jeden z najgłośniejszych kawałków rapera.' },
      { title: 'To nie jest hip-hop', artist: 'Quebonafide', year: '2014',
        lyric: 'Prowokacyjna deklaracja młodego rapera, że robi coś po swojemu, ponad gatunkowymi szufladkami.' },
      { title: 'Siła i Honor', artist: 'Kękę', year: '2016',
        lyric: 'Osobisty, motywacyjny kawałek o wartościach, wytrwałości i wierności zasadom; znak rozpoznawczy rapera.' },
      { title: 'Pełnia', artist: 'Eldo', year: '2005',
        lyric: 'Liryczny, nocny kawałek o tęsknocie i refleksji; jeden z bardziej osobistych numerów warszawskiego rapera.' },
      { title: 'Priorytety', artist: 'Paktofonika', year: '2000',
        lyric: 'Kawałek o porządkowaniu spraw i wartości w życiu; klasyk katowickiej grupy z debiutu.' },
      { title: 'Ulica', artist: 'PRO8L3M', year: '2015',
        lyric: 'Nowoczesny, mroczny duet rapera i producenta o życiu miasta; surowy klimat i charakterystyczna produkcja.' },
      { title: 'Wosk', artist: 'Taco Hemingway', year: '2016',
        lyric: 'Letni, nostalgiczny kawałek o ulotnych wspomnieniach topniejących jak wosk; popis nastrojowej produkcji.' },
      { title: 'Bzdet', artist: 'Liroy', year: '1995',
        lyric: 'Zadziorny, prześmiewczy kawałek z pionierskiego albumu polskiego rapu lat 90.' },
      { title: 'Nie wierzę nikomu', artist: 'Peja / Slums Attack', year: '2001',
        lyric: 'Nieufny, twardy manifest o zdradzie i ostrożności wobec ludzi; klasyk poznańskiego ulicznego rapu.' },
      { title: 'Mój świat', artist: 'Kękę', year: '2017',
        lyric: 'Intymny, szczery kawałek o własnym świecie, rodzinie i tym, co naprawdę ważne.' },
      { title: 'Magia', artist: 'Kaliber 44', year: '1996',
        lyric: 'Surrealistyczny, mroczny kawałek z przełomowego albumu śląskiej grupy; abstrakcyjne, oniryczne wersy.' },
      { title: 'Deszcz na betonie', artist: 'Taco Hemingway', year: '2016',
        lyric: 'Melancholijny, miejski kawałek o samotności w wielkim mieście; deszcz jako tło zadumy.' },
      { title: 'Czysta brudna prawda', artist: 'Peja / Slums Attack', year: '2007',
        lyric: 'Bezkompromisowy kawałek poznańskiego rapera o mówieniu prawdy prosto w oczy, bez upiększeń.' }
    ]
  },

  'rap-pl-zagadka': {
    label: 'rap PL — zagadki', desc: 'kryptyczny opis — zgadnij', kind: 'lyrics',
    songs: [
      { title: 'Plus i minus', artist: 'Kaliber 44', year: '1996',
        lyric: 'Śląskie trio z połowy lat 90.; abstrakcyjny, mroczny kawałek nazwany dwoma przeciwstawnymi znakami.' },
      { title: 'Ja to ja', artist: 'Paktofonika', year: '2000',
        lyric: 'Z legendarnego debiutu katowickiej grupy; afirmacja tożsamości — bohater jest dokładnie tym, kim jest.' },
      { title: 'Chwile ulotne', artist: 'Paktofonika', year: '2002',
        lyric: 'Nostalgiczny kawałek z drugiego albumu, nagrany już w cieniu tragedii; o przemijaniu i zatrzymywaniu momentów.' },
      { title: 'Tylko dla dorosłych', artist: 'O.S.T.R.', year: '2003',
        lyric: 'Łódzki raper-skrzypek; tytuł sugeruje treści nie dla dzieci, a w środku popis gęstego, jazzującego flow.' },
      { title: 'Ostatni dzień', artist: 'Molesta Ewenement', year: '1998',
        lyric: 'Warszawska grupa z surowego, kultowego debiutu; refleksja, jakby to miał być koniec — co byś wtedy zrobił.' },
      { title: 'Nielegalny proceder', artist: 'Hemp Gru', year: '2003',
        lyric: 'Warszawska, uliczna ekipa o twardym przekazie i wartościach; tytuł wprost mówi o czymś poza prawem.' },
      { title: 'Noc i dzień', artist: 'Pezet', year: '2004',
        lyric: 'Z klasycznego albumu z producentem Noonem; melancholijny, miastowy klimat kontrastów.' },
      { title: 'Luxus', artist: 'Eldo', year: '2003',
        lyric: 'Warszawski raper, były członek Grammatik; ironiczny kawałek o przepychu i jego pułapkach.' },
      { title: 'Kurort', artist: 'Tede', year: '2007',
        lyric: 'Warszawski raper o złotym łańcuchu; prześmiewczy przebój o wakacyjnym luzie i pozłacanym życiu.' },
      { title: 'Walka trwa', artist: 'Hemp Gru', year: '2003',
        lyric: 'Hymniczny, zadziorny kawałek warszawskiej ekipy o nieustającej codziennej walce.' },
      { title: 'Ostatni testament', artist: 'Pih', year: '2008',
        lyric: 'Szczeciński raper o mrocznym, bezkompromisowym stylu; tytuł brzmi jak pożegnalne, ostateczne słowa.' },
      { title: 'Nieidealna', artist: 'Mezo', year: '2007',
        lyric: 'Melodyjny rap o akceptacji partnerki z jej wadami; śpiewany refren i radiowy zasięg.' },
      { title: 'Nieznajoma', artist: 'Liber', year: '2011',
        lyric: 'Popowo-rapowy przebój ze śpiewanym refrenem; spotkanie z tajemniczą kobietą, której się jeszcze nie zna.' },
      { title: 'My Słowianie', artist: 'Donatan & Cleo', year: '2013',
        lyric: 'Folkowo-rapowy fenomen z eurowizyjnym rodowodem; dumna, prześmiewcza pochwała słowiańskich atutów.' },
      { title: 'Czarne Porsche', artist: 'Young Multi', year: '2018',
        lyric: 'Młodzieżowy, melodyjny hit o nocnej jeździe wymarzonym autem w mrocznym kolorze.' },
      { title: 'Bubbletea', artist: 'Quebonafide', year: '2017',
        lyric: 'Egzotyczny, popowo-rapowy przebój nazwany modnym azjatyckim napojem z kuleczkami.' },
      { title: 'Robaki', artist: 'Quebonafide', year: '2019',
        lyric: 'Klimatyczny, melodyjny kawałek o rozkładzie i przemijaniu, symbolizowanym przez pełzające stworzenia.' },
      { title: 'Cafe Belga', artist: 'Taco Hemingway', year: '2017',
        lyric: 'Warszawski raper; kawałek nazwany konkretnym lokalem, leniwy, miastowy klimat letniego popołudnia.' },
      { title: 'Tamagotchi', artist: 'Taco Hemingway', year: '2017',
        lyric: 'Kawałek nazwany elektronicznym zwierzakiem z lat 90.; metafora relacji, którą trzeba ciągle karmić.' },
      { title: 'Kiss cam', artist: 'Mata', year: '2021',
        lyric: 'Młody raper z głośnego debiutu; melodyjny przebój nazwany stadionową kamerą wyłapującą całujące się pary.' },
      { title: 'Wszystko proste', artist: 'Paluch', year: '2016',
        lyric: 'Białostocki raper o twardym, ulicznym wizerunku; motywacyjny ton, że da się ułożyć życie po swojemu.' },
      { title: 'Outsider', artist: 'Białas & Lanek', year: '2018',
        lyric: 'Melodyjny kawałek o byciu z boku, poza układem; przebój młodszego pokolenia rapu.' },
      { title: 'Reprezentuję biedę', artist: 'Zip Skład', year: '2001',
        lyric: 'Zbiorowa warszawska ekipa końca lat 90.; surowy obraz życia bez pieniędzy z dumnie postawioną tezą.' },
      { title: 'Życie jak wyrok', artist: 'Trzeci Wymiar', year: '2007',
        lyric: 'Mroczny, uliczny kawałek o codzienności odczuwanej jak kara, którą trzeba odsiedzieć.' },
      { title: 'Krew Krew', artist: 'Hemp Gru', year: '2007',
        lyric: 'Warszawska, uliczna ekipa; mocny, hymniczny kawałek o lojalności i więzach silniejszych niż słowa.' },
      { title: 'Sangria', artist: 'Białas', year: '2017',
        lyric: 'Letni, melodyjny przebój nazwany hiszpańskim trunkiem; lekki, wakacyjny klimat młodego rapu.' },
      { title: 'Plankton', artist: 'Guzior', year: '2018',
        lyric: 'Alternatywny, mroczny raper ze Śląska; nietypowy tytuł z morskich głębin jako metafora bycia małym trybikiem.' },
      { title: 'Diablo', artist: 'Malik Montana', year: '2019',
        lyric: 'Ciężki, drillowy kawałek o ulicznym, niebezpiecznym wizerunku; tytuł nawiązuje do diabła.' },
      { title: 'Marmur', artist: 'Sarius', year: '2017',
        lyric: 'Emocjonalny, ciężki kawałek o twardości i chłodzie relacji porównanych do kamienia.' },
      { title: 'Tak miało być', artist: 'O.S.T.R.', year: '2010',
        lyric: 'Refleksyjny, pogodzony z losem kawałek łódzkiego rapera o akceptacji tego, jak potoczyło się życie.' }
    ]
  }

};
